### ISSUE TITLE
Fluxograma do colaborador

### ISSUE THREAD

**Issue by dragonfatec** [dragonfatec/projeto2023#12]
Descrever o fluxograma do colaborador, com as funções e caminhos que serão utilizados pelo mesmo

**Comment by dragonfatec** [comment]
[Colaborador.drawio.pdf](https://github.com/dragonfatec/projeto2023/files/11065518/Colaborador.drawio.pdf)

**Comment by Gustavo394** [comment]
[1 - Diagrama colaborador.zip](https://github.com/dragonfatec/projeto2023/files/11092784/1.-.Diagrama.colaborador.zip)
Atividade concluída conforme o planejado

**Comment by Gustavo394** [comment]
![1 - Diagrama colaborador](https://user-images.githubusercontent.com/111407920/229246566-21a9f6b5-6f6d-474c-bd6c-e5623bae2a59.png)
