### ISSUE TITLE
Fluxograma do gestor

### ISSUE THREAD

**Issue by dragonfatec** [dragonfatec/projeto2023#13]
Descrever o fluxograma do gestor, com as funções e caminhos que serão utilizados pelo mesmo

**Comment by dragonfatec** [comment]
[Gestor.drawio.pdf](https://github.com/dragonfatec/projeto2023/files/11065529/Gestor.drawio.pdf)

**Comment by Gustavo394** [comment]
[2 - Diagrama gestor.zip](https://github.com/dragonfatec/projeto2023/files/11092797/2.-.Diagrama.gestor.zip)
Atividade concluída conforme o planejado

**Comment by Gustavo394** [comment]
![2 - Diagrama gestor](https://user-images.githubusercontent.com/111407920/229246593-018e943b-db20-443b-b36e-e3976f4629ab.png)
