### ISSUE TITLE
Fluxograma do administrador

### ISSUE THREAD

**Issue by dragonfatec** [dragonfatec/projeto2023#14]
Descrever o fluxograma do administrador, com as funções e caminhos que serão utilizados pelo mesmo

**Comment by Gustavo394** [comment]
[3 - Diagrama administrador.zip](https://github.com/dragonfatec/projeto2023/files/11092805/3.-.Diagrama.administrador.zip)
Atividade concluída conforme o planejado

**Comment by Gustavo394** [comment]
![3 - Diagrama administrador](https://user-images.githubusercontent.com/111407920/229246608-637b8fab-f51e-4677-a92c-89bf1dbf4b04.png)

**Comment by Gustavo394** [comment]
![3 - Diagrama administrador](https://user-images.githubusercontent.com/111407920/230245694-d61bbdc7-0e6d-4063-97d7-e583f4f7a208.png)
