### ISSUE TITLE
Diagrama do banco de dados

### ISSUE THREAD

**Issue by dragonfatec** [dragonfatec/projeto2023#15]
Modelar e desenvolver o diagrama de ligações do banco de dados

**Comment by Gustavo394** [comment]
Em processo de finalização

**Comment by Gustavo394** [comment]
![4 - Diagrama de banco de dados](https://user-images.githubusercontent.com/111407920/229246255-d6eff230-0db7-49ff-8cfb-3aebd0f23538.png)
Diagrama finalizado

**Comment by Gustavo394** [comment]
![4 - Diagrama de banco de dados](https://user-images.githubusercontent.com/111407920/229246327-e87ecff6-d0da-4db2-9da2-59ced23564f9.png)
Diagrama finalizado
