### ISSUE TITLE
Tela de recursos do colaborador

### ISSUE THREAD

**Issue by Gustavo394** [dragonfatec/projeto2023#21]
Desenvolver a tela de resursos do colaborador de acordo com os fluxogramas e wireframes.

**Comment by aleclr** [comment]
![Screenshot_30](https://user-images.githubusercontent.com/43094055/232249483-3f2063c7-3b5c-48d4-9026-6444fc546768.png)

Tela de recursos do colaborador, para registro de horas, feito com javafx e scenebuilder
