### ISSUE TITLE
Criar método de registrar hora

### ISSUE THREAD

**Issue by Gustavo394** [dragonfatec/projeto2023#22]
Criar o método onde o usuário vai conseguir registrar:
Data e hora de início, data e hora fim, justificativa e o tipo de hora (extra ou sobreaviso),
Também será armazenado a data e hora que está sendo criado este registro.

**Comment by pabloo-cunha** [comment]
Foi feita a junção do front-end do projeto com o back para a subir as horas para o banco de dados. Foi feito também alguns tratamentos para evitar erros, como: Impossibilidade de inserir letras ou simbolos onde precisa de numeros, alem de limitar a quantidade de caracter nos campos para corresponder ao esperado (HH:mm).
